### ISSUE TITLE
Incorrect Comparison Operator for Maximum Length Validation in generated code

### ISSUE THREAD

**Issue by adklempner** [ipfs/protons#132]
I've encountered an issue in the code generated from a protobuf definition after upgrading to latest version of protons, specifically in the handling of maximum length validation for repeated fields. The current implementation uses the `===` operator to check if the length of a field exceeds the maximum length defined by `opts.limits`. e.g.: https://github.com/waku-org/js-waku/pull/1898/files/29d7811d0a5ff5a88e5d90613bc137a391d94298#diff-e9813787c8ee34fed560f92abc53d0ebd289d2337f6f546dd8dcaff59b8e3105R129 This seems to be an incorrect approach, as it only throws an error when the length is exactly equal to the maximum limit, rather than exceeding it.

**Comment by wemeetagain** [comment]
:+1: definitely seems like a bug

**Comment by achingbrain** [comment]
It's not a bug, the code pushes individual values as they are read and the check is performed before the push so the error is thrown if the collection is at the limited size already.  Consequently it'll never grow above the size limit so `.length === limit` is sufficient.
