### ISSUE TITLE
Doesn't respect optional fields when using proto2 syntax

### ISSUE THREAD

**Issue by mpetrunic** [ipfs/protons#34]
Example: https://github.com/libp2p/js-libp2p-daemon/pull/94

**Comment by mpetrunic** [comment]
I don't think this is fixable unless there is a way to distinguish proto2 vs proto3 sytax here: https://github.com/ipfs/protons/blob/master/packages/protons/src/index.ts#L121
cc @achingbrain

**Comment by BigLep** [comment]
2022-06-07 conversation: we're going to throw an error if we see proto2 syntax.

**Comment by MarcoPolo** [comment]
> 2022-06-07 conversation: we're going to throw an error if we see proto2 syntax.

I don't think this is a viable solution. Right now, we have a lot of proto2 definitions.
