### ISSUE TITLE
Move the IPFS org so that it is easier to maintain?

### ISSUE THREAD

**Issue by diasdavid** [ipfs/protons#4]
Completely missed https://github.com/dignifiedquire/protons/pull/3 from my radar

**Comment by dignifiedquire** [comment]
Fiiiiine (tm) , take all my code

**Comment by diasdavid** [comment]
@dignifiedquire any update here? I'm looking for to have https://github.com/ipfs/js-ipfs/issues/1128 solved

**Comment by dignifiedquire** [comment]
I can move it but that doesn't help you with the linked issue as far as I can tell

**Comment by diasdavid** [comment]
I wanted to get this https://github.com/ipfs/protons/pull/3 released and I couldn't

**Comment by diasdavid** [comment]
thank you!
