### ISSUE TITLE
Why don't write when enum field value is 0

### ISSUE THREAD

**Issue by skysbird** [ipfs/protons#77]
https://github.com/ipfs/protons/blob/51746ec22fcc4337e3975a2a5eff871b336ab5e9/packages/protons/src/index.ts#L405

    message HopMessage {
       enum Type {
         RESERVE = 0;
         CONNECT = 1;
         STATUS = 2;
     }
      required Type type = 1;
      optional Peer peer = 2;
      optional Reservation reservation = 3;
      optional Limit limit = 4;
      optional Status status = 5;
       }

When I protons this proto, it will gnenerate the code like this:

    export const codec = (): Codec<HopMessage> => {
    if (_codec == null) {
      _codec = message<HopMessage>((obj, w, opts = {}) => {
        if (opts.lengthDelimited !== false) {
          w.fork()
        }

        if (opts.writeDefaults === true || (obj.type != null && ___TypeValues[obj.type] !== 0) {
          w.uint32(8)
          HopMessage.Type.codec().encode(obj.type, w)
        }

This will cause the wrong binary data(MALFORM) when I encode the HopMessage with type value is RESERVE when the relay node is kubo

**Comment by achingbrain** [comment]
```
  required Type type = 1;
```

`required` has been removed from proto3.

To simulate it on the wire, mark the field `optional`, then a value will always be written into the protobuf, even if it's the default value, and proto2 parsers will be able to decode the message.

**Comment by ckousik** [comment]
> ```
>   required Type type = 1;
> ```
> 
> `required` has been removed from proto3.
> 
> To simulate it on the wire, mark the field `optional`, then a value will always be written into the protobuf, even if it's the default value, and proto2 parsers will be able to decode the message.

Wouldn't this mean the value would not be written if not explicitly set. This would cause a well formatted proto3 message to fail when being decoded in proto2.

**Comment by achingbrain** [comment]
Agreed, but there's no other way to ensure the value is written onto the wire in proto3.

Consider this:

```
syntax = "proto3"
message Hop {
  enum Type {
    RESERVE = 0;
    ...
  }
  Type type;
}
```

With this definition `{ type: 0 }` would also be serialized to an empty slice and a proto2 parser would fail to read it.

It's better to upgrade everyone to proto3 and not use `required` - even Google [express some pretty strong caveats](https://protobuf.dev/programming-guides/proto/#specifying-rules) over using that keyword.

Where that isn't possible the only thing you can do is mark it `optional` and enforce the field presence at the application level.

**Comment by skysbird** [comment]
related with this issue https://github.com/libp2p/specs/pull/506
